#!/usr/bin/env bash
# Week 0 / Step 1 — WSL2 실험 환경 구축
#
# 설계 메모:
#   - 코드(repo)는 /mnt/d 에 두되, venv 와 데이터/shuffle 은 반드시 ext4 에 둔다.
#     /mnt/d 는 SATA HDD + 9p 라서 shuffle 경로로 쓰면 측정이 전부 오염된다.
#   - ext4.vhdx 는 C: (NVMe) 위에 있으므로 ext4 경로가 유일하게 믿을 수 있는 저장소다.
set -euo pipefail

VENV="${SPARK_SKEW_VENV:-$HOME/.venvs/sparkskew}"
DATA="${SPARK_SKEW_DATA:-$HOME/spark-skew-data}"
SCRATCH="${SPARK_SKEW_SCRATCH:-$HOME/spark-skew-scratch}"

echo "=== [1/5] apt packages ==="
sudo apt-get update -qq
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
  python3-pip python3-venv sysstat linux-tools-common >/dev/null
echo "  ok: python3-pip python3-venv sysstat"

echo "=== [2/5] venv @ $VENV (ext4) ==="
mkdir -p "$(dirname "$VENV")"
[ -d "$VENV" ] || python3 -m venv "$VENV"
"$VENV/bin/pip" install -q --upgrade pip
"$VENV/bin/pip" install -q "pyspark==4.0.1" pandas pyarrow matplotlib
echo "  ok: $("$VENV/bin/python" -c 'import pyspark;print("pyspark", pyspark.__version__)')"

echo "=== [3/5] data / scratch dirs (ext4, NVMe-backed) ==="
mkdir -p "$DATA" "$SCRATCH/local" "$SCRATCH/eventlog" "$SCRATCH/warehouse"
echo "  data    : $DATA"
echo "  scratch : $SCRATCH   (spark.local.dir -> $SCRATCH/local)"

echo "=== [4/5] 환경 파일 생성 ==="
cat > "$HOME/.spark-skew-env" <<EOF
# generated by env/setup-wsl.sh
export SPARK_SKEW_VENV="$VENV"
export SPARK_SKEW_DATA="$DATA"
export SPARK_SKEW_SCRATCH="$SCRATCH"
export JAVA_HOME="\$(dirname \$(dirname \$(readlink -f \$(which java))))"
export PATH="$VENV/bin:\$PATH"
EOF
echo "  ok: ~/.spark-skew-env   (source 해서 사용)"

echo "=== [5/5] 검증 ==="
# shellcheck disable=SC1090
source "$HOME/.spark-skew-env"
python -c "
import pyspark, sys, os
print('  python     :', sys.version.split()[0])
print('  pyspark    :', pyspark.__version__)
print('  JAVA_HOME  :', os.environ.get('JAVA_HOME'))
"
java -version 2>&1 | head -1 | sed 's/^/  java       : /'
df -h "$DATA" | tail -1 | awk '{print "  data fs    : "$2" total, "$4" free  ("$6")"}'

echo
echo "완료. 다음: source ~/.spark-skew-env"
